apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
spec:
  template:
    metadata:
      name: mongodb-pods
      labels:
        database: contactdb
    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          # env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: mongouser
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: mongopass
          envFrom:
            - configMapRef:
                name: mongo.config
            - secretRef:
                name: mongo.secret
      restartPolicy: Always 
  selector: 
    matchLabels:
      database: contactdb

--- 
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    database: contactdb 