server:
  port: 9000

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DB:contacts_db}
      port: ${MONGO_PORT:27017}
      authentication-database: ${MONGO_AUTH_DB:admin}
      username: ${MONGO_USER:mongouser}
      password: ${MONGO_PASSWORD:mongopass}

management:
  endpoints:
    web:
      exposure:
        include: "*"