apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
        app: myservice
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80