apiVersion: networking.k8s.io/v1
kind: 
metadata:
  name: 
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path:
            pathType: Prefix
            backend:
              service:
                name: 
                port:
                  number:  
