apiVersion: v1
kind: 
metadata:
  name: 
  labels:
spec:
  storageClassName: manual
  capacity:
    storage: 
  accessModes:
    - 
  hostPath:
    path: 

-----
  awsElasticBlockStore:
    volumeID: <volumeID>
    fsType: ext4   

accessModes - ReadOnly, ReadWriteOnce, ReadWriteMany

---

apiVersion: v1
kind: 
metadata:
  labels:
  name: 
spec:
  accessModes:
  - 
  resources:
    requests:
      storage: 