# apps/v1 ReplicaSet
apiVersion: apps/v1
kind: 
metadata:
  name: 
  labels:
spec:
  template:
    metadata:
      name: 
      labels:
    spec:
      containers:
        - name: 
          image:  
  replicas: 
  selector: 
    matchLabels:
